# Generated by Django 5.0 on 2023-12-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bloodbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgroup', models.CharField(max_length=4)),
                ('quantity', models.IntegerField()),
                ('donated_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=7)),
                ('donor_bloodgroup', models.CharField(max_length=4)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=7)),
                ('patient_bloodgroup', models.CharField(max_length=4)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
